### ISSUE TITLE
what about adding an external overlay wallhack without glu 

### ISSUE THREAD

**Issue by Alias95** [XanOpiat/Python-CSGO-Cheat#101]
Hey , what about  adding an external wallhack without glu ? I mean if we can get the position of the enemy , you can draw a box on that 

by doing this you can even do a live stream by sharing the game layout so people gonna only see the game but you have  the  enemy wh on your screen ? 

just something to think on in the future, I'm trying to apply that on your cheat but I'm not too experience on python.   will do my best if I can help. it's just an idea and your are free to apply that  or not as I know you have lots of stuff other than this cheat . thanks for all your effort anyway.

I have some resource that might  help : 

https://github.com/djblackops/DunkWare ( the cheat is not working but seems like he has some good work there ) 

https://github.com/qb-0/PyMeow/blob/master/examples/csgo_esp.py ( I have tested this already and it's working perfect but not sure if you really need to apply PyMeow here ) .

**Comment by XanOpiat** [comment]
Definetly a cool idea, will take a look and get back to you

**Comment by Alias95** [comment]
perfect, I got some more resources that might help . 

https://github.com/ALEHACKsp/Meow-CSGo/blob/5e9beb28518f352ba2029fd298b8c62fdfa55930/main.py#L126

![image](https://user-images.githubusercontent.com/26596347/152708144-a9632f91-d5be-4e48-9468-39a98c00c371.png)
