### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shahram08** [XanOpiat/Python-CSGO-Cheat#106]
there is some  bug u should fix it 
first  rcs  if u try ur self reapating fire with ak and m4 u will see there is bug and mouse going so much down
if u can add aimassisst  better then silent aim 
ty for sharing your soft its amazing

**Comment by shahram08** [comment]
there is Question . this python is safe to use ? on main account

**Comment by Ricardo04santos** [comment]
yes

**Comment by XanOpiat** [comment]
> 

there is actually aim assist, basically you just have to use soft aimbot, you can disable the silent aim in settings

**Comment by XanOpiat** [comment]
aim assist would for example a low fov, smooth aimbot
so setting aimfov to 15 for example
and smoothness to some value that works for you

**Comment by XanOpiat** [comment]
when it comes to the rcs:
this is actually a very wierd issue i have been having problems with for a while, ill look into it once more.
problem is that the rcs seems to be working for some people (including me) and for some it isnt.
im assuming it has to do with some csgo specifig setting but im not sure

**Comment by XanOpiat** [comment]
yeah i just etested for me the rcs works, maybe try restarting your game
