### ISSUE TITLE
getting this issue when running this 2nd file projectx 

### ISSUE THREAD

**Issue by ibbizaki123** [XanOpiat/Python-CSGO-Cheat#108]
![image](https://user-images.githubusercontent.com/15956995/172705144-90234c37-3ef0-4211-b1a0-e79c176fd37f.png)

**Comment by XanOpiat** [comment]
you are not running the correct command. "python projectx_v2.py"

**Comment by ibbizaki123** [comment]
my bad it requires administrator previlege*
