### ISSUE TITLE
Never had this issue. 

### ISSUE THREAD

**Issue by ZelKed** [XanOpiat/Python-CSGO-Cheat#109]
![image](https://user-images.githubusercontent.com/76404202/174441726-387d2502-dfd6-44d7-a29d-9f1b0cc39e44.png)

do u know why this happens?

**Comment by XanOpiat** [comment]
You propably didnt download the cheat correctly, make sure you have all the directories that you can also find github on your pc

**Comment by XanOpiat** [comment]
It might also be helpful to post the entire error message
