### ISSUE TITLE
[QUESTIONS] About PyMem

### ISSUE THREAD

**Issue by slhrlx** [XanOpiat/Python-CSGO-Cheat#43]
1.vac detects PyMem? 
2. if i make my own cheat, writed line by line by me, have chance to get detected by VAC?

**Comment by XanOpiat** [comment]
It technically can, you wont get banned however, i suggest taking a look at this post https://guidedhacking.com/threads/how-to-bypass-vac-valve-anti-cheat-info.8125/ if you wanna find out more

**Comment by slhrlx** [comment]
wow, thank you a lot bro! ;D I'm starting with cheats on PC now, I only made cheats for android, thanks for the help!
