### ISSUE TITLE
Offset Dumping Issues

### ISSUE THREAD

**Issue by Konvikt** [XanOpiat/Python-CSGO-Cheat#44]
I dumped offsets for the update with the hzd config you gave me, but the cheat isn't functioning.

I don't mind waiting for you to do it, just need help understanding how for myself.

**Comment by XanOpiat** [comment]
Im sorry, didnt realise their was an update
i can show you how to dump them yourselvee wait

**Comment by XanOpiat** [comment]
![image](https://user-images.githubusercontent.com/62156037/118959217-68232780-b962-11eb-998b-f5028a79705c.png)
change the path in offsets to th location of your csgo.json file (where your hazedumper exe is)

**Comment by XanOpiat** [comment]
Also i will update the cheat this weekend (exams are on break), and the update will include actual auto updates using sig and netvar scanning
