### ISSUE TITLE
[HELP] Triggerbot delay

### ISSUE THREAD

**Issue by slhrlx** [XanOpiat/Python-CSGO-Cheat#45]
https://github.com/XanOpiat/Python-CSGO-Cheat/blob/7248e05f895498536ea7a8c452d4a3f9e40134ac/ProjectX.py#L589

 I'm trying to add a delay to this triggerbot, how I can make this? I tried use this, but, don't worked:
{....
delay = 0.100
pm.write_int( client + delay + dwForceAttack, 6 )
...}
[ I made the correct imports on the code and all is fine, but I rly can't add a delay between this ]

**Comment by XanOpiat** [comment]
so you just wrote the lines 
delay = 0.100
?
You know that you have to do something like:
time.sleep(0.1)
for this you would need to import the time module at the beginning with the other imports as following:
import time

**Comment by slhrlx** [comment]
Hi, I forget to back here to say for you what I made :D

I created a def which generates a random delay for time.sleep, after this, I call the function what I made after the "if entity_id > 0"..... and, before write on memory, thanks for all :D

If you want, you can close this thread (sry for the bad English)

**Comment by XanOpiat** [comment]
So its working now?

**Comment by slhrlx** [comment]
Yeah!  :D

**Comment by XanOpiat** [comment]
n1
