### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by DebilekMatysek** [XanOpiat/Python-CSGO-Cheat#46]
Im having a small issue with installing that cheat. I have done everything u said and it didnt work. Can someone help me please? 
![image](https://user-images.githubusercontent.com/84984894/120014183-0ad24a80-bfe2-11eb-9228-1ed29e63a64c.png)

**Comment by XanOpiat** [comment]
Oh yikes that ones on me you dont need to install ctypes, its preinstalled with python. The cheat should still work, atleast if you installed the other modules

**Comment by XanOpiat** [comment]
Updated requirements.txt
