### ISSUE TITLE
DevisionByZero

### ISSUE THREAD

**Issue by JacobSckota** [XanOpiat/Python-CSGO-Cheat#48]
![image](https://user-images.githubusercontent.com/83134482/124489025-34d51480-ddb9-11eb-9758-3390d8d21c88.png)

**Comment by JacobSckota** [comment]
also, it tells me to use another fov value while Im using 100 fov value

**Comment by Undefeatable420** [comment]
both of these happen to me too

**Comment by XanOpiat** [comment]
There are 2 fov values, one is for the fovchanger, the other one for the fov of the aimbot, the divison by zero error should be fixed
