### ISSUE TITLE
wh doesnt work

### ISSUE THREAD

**Issue by carecabarbudoxd69** [XanOpiat/Python-CSGO-Cheat#52]
Hello, ive noticed that wh doesnt work!! 
Idk if it is a problem of my pc or if it is something in the code thats wrong 
This has been a problem to me for like 1/2 months

**Comment by XanOpiat** [comment]
Could you try again?, i changed the code today and for me its working, you need to download the recent file

**Comment by carecabarbudoxd69** [comment]
oh yeah it is working no ty
