### ISSUE TITLE
CS 1.6

### ISSUE THREAD

**Issue by GitHuber90** [XanOpiat/Python-CSGO-Cheat#54]
Hey, I really like these cheats! And I would like to ask if you could do the same cheats for cs 1.6? It would be amazing!

**Comment by XanOpiat** [comment]
I actually dont own 1.6, so i wouldnt be able to test the cheats, i will take a look tho, if there are enough possibilieties in that game, i might buy it

**Comment by GitHuber90** [comment]
Alright, thanks!
