### ISSUE TITLE
Could not read memory at: 46056, length: 4 - GetLastError: 299

### ISSUE THREAD

**Issue by luizpalazzo** [XanOpiat/Python-CSGO-Cheat#56]
Hi,

I am getting an infinite looping with this message:

Round not started yet

I inserted an print exception in the piece of code:

              try:
                    player = pm.read_int( client + dwLocalPlayer )
                    engine_pointer = pm.read_int( engine + dwClientState )
                    glow_manager = pm.read_int( client + dwGlowObjectManager )
                    crosshairID = pm.read_int( player + m_iCrosshairId )
                    getcrosshairTarget = pm.read_int( client + dwEntityList + (crosshairID - 1) * 0x10 )
                    immunitygunganme = pm.read_int( getcrosshairTarget + m_bGunGameImmunity )
                    localTeam = pm.read_int( player + m_iTeamNum )
                    crosshairTeam = pm.read_int( getcrosshairTarget + m_iTeamNum )
                except Exception as e:
                    print( "Round not started yet" )
                    print(e)
                    time.sleep( 5 )
                    continue

And i am getting this message:

Could not read memory at: 46056, length: 4 - GetLastError: 299

Could you please help me? I can pay if needed. Thanks!

**Comment by luizpalazzo** [comment]
I am also running in administrator mode. Pymen version 1.8.5. I also tried with other versions but i am still getting this error.

**Comment by XanOpiat** [comment]
yeah this is kinda wierd, are you sure you are already on a map when running the cheat? for me this error doesnt happen, maybe you could try again, this error is completely normal tho when you are still in the main menu

**Comment by luizpalazzo** [comment]
yeah, i am on the map. Could you please share with me your python version and dependancy versions? It was working fine yesterday, but during night i got this error and still persists.

**Comment by XanOpiat** [comment]
very wierd im using python 3.8, pymem 1.8.3

**Comment by luizpalazzo** [comment]
Hi,

I tested using pymem 1.8.3 and now its working.

Thanks!

**Comment by XanOpiat** [comment]
very wierd, np tho
