### ISSUE TITLE
i am banned

### ISSUE THREAD

**Issue by SheDontDo** [XanOpiat/Python-CSGO-Cheat#57]
bro i thought this cheatings not detected by vac secure. now i been banned by vac on competitive

**Comment by Konvikt** [comment]
You can't be vac banned from specifically competitive, if you are banned from competitive that is called an overwatch ban, and you were too blantant. :shrug:

**Comment by XanOpiat** [comment]
are you sure you are vac banned? maybe you can leave you steam profile so i can check, also which cheats where you using, if it was silentaim with a high aimbot fov it may have been a ban by vacnet

**Comment by SheDontDo** [comment]
yes im sure it writes 1 VAC ban on record | Info
4 day(s) since last ban

i was using bunnyhop and wallhack and radar, nothing else. No aimbot, silentman, fov changer or anything else

**Comment by XanOpiat** [comment]
im again asking you to leave your profile for me to verify, it seems very wierd that your the only person to get vac banned using this cheat and only after 4 days of playing. Also i never said that the cheat would be completely safe, no cheat is, especially no external one. I only stated that i used this cheat for probably around 400hrs and never been banned even when using aimbot or other features. Also i know a lot of people that used this cheat without getting banned. Are you sure you havent used any other cheat in the past? Vac Bans can be as delayed as 6 months from the last time using the cheat

**Comment by XanOpiat** [comment]
I will make a new steam now and play with the exact cheat you used, will see how it goes

**Comment by XanOpiat** [comment]
how many hours did you have with the cheat?

**Comment by XanOpiat** [comment]
I have around 100hrs on a new acc with the cheat now, havent been banned, he is not answering anymore, so im closing this now
