### ISSUE TITLE
Entity Reading issue

### ISSUE THREAD

**Issue by pb1337** [XanOpiat/Python-CSGO-Cheat#59]
Hi there, Currently working on a modification to your base. 
I was wondering why this sometimes returns a negative value and causes the whole thing to break. 
I have restarted CS and Computer multiple times and still the same error.
Any help would be appreciated. 
`entity = pm.read_int(client + dwEntityList + i * 0x10)`
`print(entity)`
`Output: -2014494064`

**Comment by XanOpiat** [comment]
how exactly is the script breaking?  normally this error should be caught by the except statement. Maybe you could provide the exact error
