### ISSUE TITLE
How to change Antivac Variable from time to time? 

### ISSUE THREAD

**Issue by Elejido** [XanOpiat/Python-CSGO-Cheat#60]
i appreciate your work, do you have a tutorial to to change antivac variable? 

best

**Comment by XanOpiat** [comment]
its not that hard, just 
open the .py file with a editor like notepad or an ide
than scroll down to the variable and just change the string after the "="

**Comment by Elejido** [comment]
gotcha...so i went down to the variable "antivac = xdjweiofjwfjoifjoijfopfjo4ij" but when i change it, the tool is not starting anymore? does it need the same length or why?

**Comment by XanOpiat** [comment]
it should be starting as normal, length doesnt matter, maybe you changed another line by accident, is there any error message?
