### ISSUE TITLE
Mouse Bind

### ISSUE THREAD

**Issue by 2to2filuk** [XanOpiat/Python-CSGO-Cheat#63]
how can i bind my mouse for this? tried mb4 didnt work, tried mousebutton4 still not working

**Comment by XanOpiat** [comment]
sorry right now  this isnt possible as im using the keyboard module which only allows keybinds

**Comment by 2to2filuk** [comment]
when will we get that update? I'm excited

**Comment by XanOpiat** [comment]
Updatet just now, should be working, use MB5, MB4, ML, MR and wheel as binds, also there sometimes is a bit on inconsistency maybe you could give me somre more feedback

**Comment by 2to2filuk** [comment]
Nice Work very clean! i really wanted to use this on FACEIT, i want to help bypass this

**Comment by XanOpiat** [comment]
yeah faceit isnt really bypassable atm, also you would have to leave python and go fully internal, the best thing you can do imo is make a hardware cheat, but the hardware itself is kinda expensive

**Comment by 2to2filuk** [comment]
yeah love the work bro! hope we can run this on faceit ac

**Comment by 2to2filuk** [comment]
oh one thing are you interested in creating some stuffs like this for valorant?

**Comment by XanOpiat** [comment]
As i said, you cant cheat with python on faceit or on valorant
