### ISSUE TITLE
only ui

### ISSUE THREAD

**Issue by skymon4** [XanOpiat/Python-CSGO-Cheat#66]
only ui happen, when I start the game, wall is not work for my computer

**Comment by XanOpiat** [comment]
any error message, are the other functions of the cheat working, also you need to start the game before you start the cheat.
for me everythins is working flawlessly

**Comment by skymon4** [comment]
the interface hava any error，tomorrow I will send your the pic whth the cheat

**Comment by skymon4** [comment]
![微信截图_20210929193048](https://user-images.githubusercontent.com/33510540/135260581-d26c8c26-8e3a-4987-92a0-1437013b8e07.png)
this is my problem, I can not use aimbot
or this is wrong for my steps

**Comment by XanOpiat** [comment]
are you sure that you have thr latest version of the cheat because for me everything is working

**Comment by XanOpiat** [comment]
maybe you could show me what you dwClientStage_ViewAngles offset is. just implement a 
print(dwClientStage_ViewAngles)
 statement somewhere

**Comment by skymon4** [comment]
yeah, I clone the project in yestrerday.

**Comment by skymon4** [comment]
is not my screen is 2k?

**Comment by XanOpiat** [comment]
what do you mean? please speak proper english otherwise i cant help you.
you have to open the ProjectX.py file with an editor
and then paste this: print(dwClientState_ViewAngles)
somewhere in the main function and then tell me what it says when you run the cheat

**Comment by XanOpiat** [comment]
its very wierd that the cheat is somehow not working for you while working completely fine for me
