### ISSUE TITLE
AimBot Crashing due to invalid memory address of engine_pointer

### ISSUE THREAD

**Issue by not-coder-guy** [XanOpiat/Python-CSGO-Cheat#67]
The script is crashing when turning on the aimbot 
![image](https://user-images.githubusercontent.com/41840203/135691461-90b4afd1-73e0-46b8-93ba-02c506d9e3d2.png)

The -72548136 is the engine_pointer value and I think that is the problem any suggestions on how to solve this.

**Comment by tumkas** [comment]
Yes I got the same problem |:

**Comment by XanOpiat** [comment]
updated
