### ISSUE TITLE
several pymem pointer errors

### ISSUE THREAD

**Issue by ElOxo** [XanOpiat/Python-CSGO-Cheat#71]
i use the newest versions of Offsets.
WH, noFlash, Triggerbot, Radar and Bunny works fine.
FOVchanger i didnt tested ;)

Error Aimbot in Line 527
localpos_x_angles = pm.read_float( engine_pointer + dwClientState_ViewAngles )

Error Recoil Control in Line 633
rcs_x = pm.read_float( engine_pointer + dwClientState_ViewAngles )

Error for RankReveal in Line  706 
player_info = pm.read_int( (pm.read_int( engine.lpBaseOfDll + dwClientState )) + dwClientState_PlayerInfo )

**Comment by XanOpiat** [comment]
also you could maybe tell me what your value is for dwClientState_ViewAngles? just do print(dwClientState_ViewAngles)
somewhere after the offsets. thanks in advance

**Comment by ElOxo** [comment]
Ye i Start it works fine and if 
1) i press then a Key for Aimbot it breaks
2) i Shoot with weapon (RecoilControl)
3) i press RankReveal button

then i gets the runtime error

**Comment by XanOpiat** [comment]
> Ye i Start it works fine and if
> 
> 1. i press then a Key for Aimbot it breaks
> 2. i Shoot with weapon (RecoilControl)
> 3. i press RankReveal button
> 
> then i gets the runtime error

very wierd

**Comment by XanOpiat** [comment]
oh maybe you could also tell me what dwClientState returns

**Comment by ElOxo** [comment]
ViewAngles is 19856
ClientState is 5804012

**Comment by ElOxo** [comment]
Because there i get -64533088 and thats my problem

**Comment by ElOxo** [comment]
My enginePointer = -64552944

**Comment by ElOxo** [comment]
Hmmmmmm xD

**Comment by XanOpiat** [comment]
-72548336 this is my engine_pointer

**Comment by XanOpiat** [comment]
![image](https://user-images.githubusercontent.com/62156037/137600335-12fffec8-da53-4665-b362-23c6b03d4c27.png)
yessir

**Comment by ElOxo** [comment]
mensch sag das doch dann spare ich mir mein kack english xD

**Comment by XanOpiat** [comment]
perfekt xd
das ist aber sehr wierd

**Comment by ElOxo** [comment]
1208 is pm.process_handle

**Comment by ElOxo** [comment]
self.pm.process_handle = 956
.pm.process_handle = 1208

**Comment by XanOpiat** [comment]
wo, weil an process handle dürfte es eig nicht liegen, dumme frage von mir

**Comment by ElOxo** [comment]
in Zeile 470 steht bei dir self.pm...... oder nur pm ?

**Comment by XanOpiat** [comment]
nur pm

**Comment by rfawrh54** [comment]
please help me with my question in this section

**Comment by ElOxo** [comment]
@XanOpiat 
https://github.com/ElOxo/Python-CSGO-Cheat
kannst dir gerne Anschauen, ist identisch mit dem Quelltext aus dem Repo + in Zeile 11 bei mir habe ich den ErsatzLink falls Hazedumper mal schneller ist als du XD

**Comment by ElOxo** [comment]
v1.8.5  von pymem

**Comment by XanOpiat** [comment]
ja same xD

**Comment by XanOpiat** [comment]
geht aber bei mir auch beides

**Comment by XanOpiat** [comment]
welche python version?

**Comment by ElOxo** [comment]
Ich sehe auch das Problem und kann dich da gut nachvollziehen, dass du das nicht gefixxed bekommst. Hätte ja sein können, dass du da eine Idee hättest. 

Ich werde ansonsten nächste Woche auf Arbeit mir mal die Zeit nehmen und das Problem angehen.

**Comment by XanOpiat** [comment]
ok also was ich jetzt gefunden habe (nach exzessiven versuchen eine zweite python version ans laufen zu kriegen) tatsächlich funktioniert bei mir der cheat mit 3.9 auch nicht, zwar nicht nur aimbot sondern einfach alles aber vielleicht hat das was damit zu tun. bei mir funktionieren tut auf jeden fall 3.8.5

**Comment by XanOpiat** [comment]
junge das war wierd
weil das mit pip iwie nicht funktioniert hat, musste ich die alle über pycharm installieren

**Comment by ElOxo** [comment]
joar also auch mit python 3.8.5 bekomme ich den Selben Fehler - logisch da sich der Prozess engine.dll bei mir ja auch denkt 

LETS fuck this german guys up a bit

**Comment by XanOpiat** [comment]
so ein scheiß

**Comment by ElOxo** [comment]
Joar, also ich werde an der Stelle erstmal Schluss machen. Ich danke dir für die Zeit und die Mühe den Fehler zu finden/Fixxen.

Habe mir nochmal das angeschaut und es liegt tatsächlich alles nur an der "falschen" engine. 
Denn alles andere ist von der Engine unabhängig und daher läuft das. 

Ich werde es morgen mal auf einem anderem Gerät ausprobieren, sollte es da funktionieren, werde ich dir auf jeden Fall Bescheid geben.

Schönen Abend dir noch ;)

**Comment by XanOpiat** [comment]
verstehe ich, aber wenn du wills t könnte ich dir mal eine neue version des cheats schicken, ich habe eine mit auto offsets/sig scanning, vielleicht funktioniert die bei dir(ist noch nicht ganz fertig deshalb noch nicht auf github)

**Comment by XanOpiat** [comment]
wait so it is saying "round not started yet" all the time?

**Comment by Bugleman** [comment]
Still not fix what a shame 
Made a error going in with the full traceback

**Comment by XanOpiat** [comment]
fixed
