### ISSUE TITLE
xanax how do i update offsets by myself

### ISSUE THREAD

**Issue by carecabarbudoxd69** [XanOpiat/Python-CSGO-Cheat#76]

**Comment by owersite** [comment]
His name is not xanax and u can update offsets by using a repo that auto updates offsets inspired by Haze (creator of Hazedumper): https://github.com/Akandesh/blazedumper

**Comment by carecabarbudoxd69** [comment]
can u tell me step by step? xD

**Comment by carecabarbudoxd69** [comment]
like do i drag it to the python cheat folder

**Comment by carecabarbudoxd69** [comment]
my v2 just keeps saying round not started

**Comment by XanOpiat** [comment]
soo, atm the v2 cheat seems to be bugged for most people, but idk how to fix it because it is working for me. And about the updating offsets for the v1 cheat, im updating them rn but if you want to you can add me on dc, ill show you how to update yourself
qdk#6703

**Comment by carecabarbudoxd69** [comment]
i sent u a friend request rn :>
