### ISSUE TITLE
No Error,Not running 

### ISSUE THREAD

**Issue by Bugleman** [XanOpiat/Python-CSGO-Cheat#81]
After new update it has no error but is not running at all i update the offsets using hazedumper but when running program it runs open's gui i click update and nothing happens

**Comment by makerrii** [comment]
aah i get it working valve change cs go name now it is "Counter-Strike: Global Offensive - Direct3D 9"
so if you using older version you only need change this
![fixed](https://user-images.githubusercontent.com/93031172/146001318-f2b793e5-a0f9-424c-bceb-24f626b9f8a0.PNG)

**Comment by Bugleman** [comment]
Using V2 and i just clone the repo.

**Comment by makerrii** [comment]
It worked me v2 too. You change the cs go name? Like that pic?

**Comment by Bugleman** [comment]
Not sure i cant really understand the message he sent.
V2 isnt working as i cloned it ran it and the gui and dumping offsets work but when clicking update on the gui nothing happens

**Comment by Bugleman** [comment]
But im on windows not linux?

**Comment by Bugleman** [comment]
Ok and this is for v2 correct

**Comment by Bugleman** [comment]
This isnt for v2 
line 480 does not exist in the ProjectX_V2.py file.

**Comment by makerrii** [comment]
it is line 56 in v2. but you get the point what to do

**Comment by Bugleman** [comment]
Yes just making sure this is what i should be doing and you said this worked for you?

**Comment by makerrii** [comment]
yes

**Comment by Bugleman** [comment]
Lit ile give it a shot!

**Comment by Bugleman** [comment]
Fixed!

**Comment by XanOpiat** [comment]
thanks to both of you, im very very busy with school atm so i dont have a lot of time to fix updates, but i will take a look at every issue as soon as possible
