### ISSUE TITLE
Not stirctly an issue

### ISSUE THREAD

**Issue by dev5tar** [XanOpiat/Python-CSGO-Cheat#82]
I have some issues with the aim,  namely that I cant select Mouse 1.

But thats not why Im here. I was wondering if you could make sense of eknods scripthial regarding the recent update and dwinput. i turn to you becuase youve took python further than anyone else in CSGO, I even tried to fork your auto strafe into my own script because..WOW.

Im just a filthy paster, but I was kinda proud of what python hacks I scraped together into my own script, and even added a delay to the trigger and blocked some weapons from locking.

So to get to the point; I have a python script I need some help updating; namely the values shown here in relation to the netvars;

```
class NetVarList:
    def __init__(self):
        table = NetVarTable('DT_CSPlayer')
        self.m_fFlags = table.get_offset('m_fFlags')
        table = NetVarTable('DT_BasePlayer')
        self.m_iHealth = table.get_offset('m_iHealth')
        self.m_vecViewOffset = table.get_offset('m_vecViewOffset[0]')
        self.m_lifeState = table.get_offset('m_lifeState')
        self.m_nTickBase = table.get_offset('m_nTickBase')
        self.m_vecPunch = table.get_offset('m_Local') + 0x70

        table = NetVarTable('DT_BaseEntity')
        self.m_iTeamNum = table.get_offset('m_iTeamNum')
        self.m_vecOrigin = table.get_offset('m_vecOrigin')
        self.m_clrRender = table.get_offset('m_clrRender')

        table = NetVarTable('DT_CSPlayer')
        self.m_hActiveWeapon = table.get_offset('m_hActiveWeapon')
        self.m_iShotsFired = table.get_offset('m_iShotsFired')
        self.m_iCrossHairID = table.get_offset('m_bHasDefuser') + 0x5C
        self.m_iGlowIndex = table.get_offset('m_flFlashDuration') + 0x18

        table = NetVarTable('DT_BaseAnimating')
        self.m_dwBoneMatrix = table.get_offset('m_nForceBone') + 0x1C

        table = NetVarTable('DT_BaseAttributableItem')
        self.m_iItemDefinitionIndex = table.get_offset('m_iItemDefinitionIndex')

        self.dwEntityList = vt.entity.table - (mem.read_i32(vt.entity.function(6) + 0x22) - 0x38)
        self.dwClientState = mem.read_i32(mem.read_i32(vt.engine.function(18) + 0x21))
        self.dwGetLocalPlayer = mem.read_i32(vt.engine.function(12) + 0x16)
        self.dwViewAngles = mem.read_i32(vt.engine.function(19) + 0x191)
        self.dwMaxClients = mem.read_i32(vt.engine.function(20) + 0x07)
        self.dwState = mem.read_i32(vt.engine.function(26) + 0x07)
        self.dwButton = mem.read_i32(vt.input.function(15) + 0x21D)
        if g_glow:
            self.dwGlowObjectManager = mem.find_pattern("client.dll",
                    b'\xA1\x00\x00\x00\x00\xA8\x01\x75\x4B', "x????xxxx")
            self.dwGlowObjectManager = mem.read_i32(self.dwGlowObjectManager + 1) + 4
```
Id appreciate any help on getting this code working again. I can offer a bounty of 20$ if incentive is required. Id just really like my own script working again. Im happy for it to be open source following the changes, or you can apply a PR to Scripthial.  IF not, I can migrate to this application and offer the following suggestions;

Mouse bindings for aimlock
Aim Smoothing.

If youd like to take a look at my franken script, lmk, its basically [scriptial](https://github.com/ekknod/scripthial) with extras.

**Comment by makerrii** [comment]
Hi. I m not sure you mean mouse left putton?
If you but (ML) on aimbot key it is then mouse left putton. But yea i m curious too smoothing aimbot. I try maybe smoothing it after christmas but letsee if i get it working

**Comment by dev5tar** [comment]
The aimbot is borked to, dwinput faced some big changes in the update in prep for steamdeck.

**Comment by XanOpiat** [comment]
maybe you could add me on dc i think i can help you out better on there
qdk#6703
