### ISSUE TITLE
Bugs,Errors,Suggestions

### ISSUE THREAD

**Issue by Bugleman** [XanOpiat/Python-CSGO-Cheat#83]
Hello Its Bugleman once again I have gotten sucked into this project but got it working finaly just to find out the RCS and Aimbot are not working and when trying to bind key binds it errors a lot or even seems like it does not notice i bonded a button,

1. Keybinds are very glitchey and are very broke
2. Aimbot seems to not be working (Could be caused by the key binds issues | looking into the code)
3. GUI missing some options, the GUI is missing HealthBased for the ESP and a couple other options
4. Auto-Offsets, Adding auto-offsets such as pulling the config.json file from haze would be good so we dont need to update them. 
5. Cleaning up, clean up the code its hard to read with ( Spaces ) Between every line, Or every function.
6. LegitBot adding something like legit bot could pull in more people to use your cheat or maybe rank reveal as the last version had.

I just want to clarify this is my option and are some cool ideas for the future of this project!
Thanks for reading,
BugleMan

**Comment by XanOpiat** [comment]
1. wym keybinds are broken?
2. sorry for answering so late in the middle of exams atm

**Comment by XanOpiat** [comment]
3.  how is the aimbot not working? what is the error thrown etc?  because one again for me everything is working

**Comment by Bugleman** [comment]
1. Keybinds dont work at all as in i bind "b" or "shift" and it dont work
2. Your fine take your time.
3. Aimbot just is not working atm, no error might try debugging soon but anytime i hold down the aimbot key it does not work and makes all the other cheats turn off until i let go of the aimbot key.

Note: Theses are just suggestions, that i think could help improve this project!

**Comment by XanOpiat** [comment]
Hmm the thing with the keybinds is very interesting. are you sure there is no exception thrown? maybe you could remove the "try:" line in line 55 (projectx.py file) aswell as the "except:" and "continue" statements in line 140 and 141

**Comment by XanOpiat** [comment]
this could also help to tell me what exactly is wrong with the aimbot. also if the keybinds arent working at all, how can the aimbot cause all this trouble whenever you hit the aimbot key? if the keybinds arent working than nothing should happen if you press the aimbot key right? maybe im missing your point here but i feel like those 2 problems may be connected

**Comment by Bugleman** [comment]
When having a keybind on TriggerBot it works
When having a keybind on Aimbot it does not work meaning the issues comes from the aimbot.

Also some time's when using caps such as Shift or Alt in the keybind settings, it wont work.
Over all key-binds sometimes work and sometimes just have a mind of there own.

When pressing aimbot-key / holding it down ESP turns off indicating that the aim has to be not working or erroring in some way.

**Comment by XanOpiat** [comment]
yeah this makes more sense, this just means that the aimbot is broken and the keys are working

**Comment by trungdoanhong** [comment]
The memory value of dwEntityList and dwClientState could not be read. I've spent the last 5 days trying to fix it but couldn't. So I look forward to your update.

**Comment by makerrii** [comment]
i think it is the same problem what was beginning need add read_uint (becouse aimbot not ever worked  this new version)
after that read_uint update all anothers start working exept aimbot.
but i was added uint every place where i find it is not anymore crashing when press aim key but it is not still working
maybe i miss some ints...

**Comment by XanOpiat** [comment]
@trungdoanhong in which parts can the variables not be read? is the error happening in the Offset.py file or somewhere else

**Comment by trungdoanhong** [comment]
Error is at Offset.py file.
2 line:
..
dwEntityList = get_sig (pm1, "client.dll", rb "\ xBB .... \ x83 \ xFF \ x01 \ x0F \ x8C .... \ x3B \ xF8", 0, 1)
..
dwClientState = get_sig (pm1, "engine.dll", rb "\ xA1 .... \ x33 \ xD2 \ x6A \ x00 \ x6A \ x00 \ x33 \ xC9 \ x89 \ xB0", 0, 1)

**Comment by XanOpiat** [comment]
ok that is interesting, do you mind telling me what exactly the error is?

**Comment by trungdoanhong** [comment]
I am very sorry for the confusion in last post. Actually the error is at
**engine_pointer = pm.read_int( engine + dwClientState )**
The value of **engine_pointer** returned is -67633136.
Is aimbot still working on your computer now? I tried on 6 company computers and none of them worked. Hope the fix comes from you soon. I look forward to it every minute.

**Comment by XanOpiat** [comment]
Yeah the aimbot is still working for me

**Comment by XanOpiat** [comment]
maybe you could try now? im asuming you meant the variable in the ProjectX_V2.py file

**Comment by trungdoanhong** [comment]
I replaced all **pm.read_int( engine + dwClientState )** in other files to **pm.read_uint( engine + dwClientState )** and it worked. Thank you very much. If you give me a donate button. It would be great.

**Comment by trungdoanhong** [comment]
And this line
**entity_bone = pm.read_int(entity + m_dwBoneMatrix)**
to 
**entity_bone = pm.read_uint(entity + m_dwBoneMatrix).**

**Comment by XanOpiat** [comment]
no worries man great that we could fix the problem the cheat is very wierd atm, csgo must have changed something in their code so that reading ints isnt always enough

**Comment by trungdoanhong** [comment]
aimbot was working but the silent function is still crashing. This command line fails even when I change from int to uint:
**m_buttons = pm.read_int( OldUser + 0x30 )**

**Comment by XanOpiat** [comment]
yeah i actually encountered the same issue just know, im dealing with it atm

**Comment by trungdoanhong** [comment]
I hope you will improve the function GetBestTarget(...). When playing the game, it often happens that the crosshair is directed at the enemy behind the wall instead of the enemy in front. The enemy is even standing to the right or left of the player.

**Comment by XanOpiat** [comment]
So in the new version of the cheat the aimbot automatically locks on to the player closest to your crosshair, if you dont want the aimbot to go through walls you should enable the "only spotted" feature. This doenst work flawlessly however as the function often is about 0,5 sec behind the actual game which means that your enemy will peek you and the aimbot wont instantly lock onto him. I cant improve this in python however, as it is in interpreted language and thus cannot be used for internal cheats and bsp parsing

**Comment by XanOpiat** [comment]
So i now updated a lot of the funtions in the cheat hopefully the whole read_int thing wont be an issue again, otherwise please report it to me. I also reversed the new CIput classes and updated the silentaim which is now working again aswell. Please test the cheat and tell me if you encounter further problems, i will be sure to keep the cheat updated, especially as i have holidays now, so i have lots of time for updating and improving the program. GLHF

**Comment by trungdoanhong** [comment]
Great. Everything worked. And even better, I was discovered by VAC and CSGO
locked my game account. From now on I will have more time for family and
work. Thank you very much.

**Comment by XanOpiat** [comment]
Are you serously mad? It has to be obvious that you cant use silentaim aimbot with a high fov because this is detected by vac.
The cheat it self is not detected just because you are using it wrong. Your welcome and please learn to do use common sense

**Comment by XanOpiat** [comment]
If you dont know how the single options work dont use them... https://www.youtube.com/watch?v=JcMqaA7i8Jc&ab_channel=kEnT this is what silentaim looks like to a spectator/valve. Your crosshair instantly flicks to the enemy and back to where it was before. This is obviously easily recognized by vac soo.... if you are to dumb to understand the features its not my fault that you got banned. Oh and also
![image](https://user-images.githubusercontent.com/62156037/147236497-1d909e13-ae54-4e79-a395-a8d85428c914.png)

**Comment by trungdoanhong** [comment]
Perhaps you misunderstood me. I don't blame you, I just want to thank you
for giving me the opportunity to study cheat codes. I was too immersed in
gaming and spent very little time on work and family. I intentionally used
hacking software to get my account locked, only then can I quit CSGO.
Thank you again.

**Comment by XanOpiat** [comment]
Ah that makes more sense, then have fun working i guess
