### ISSUE TITLE
Aimbot is not working 

### ISSUE THREAD

**Issue by badrsh** [XanOpiat/Python-CSGO-Cheat#84]
Thanks a lot, the aimbot is not working at all. I was debugging the app and it always throw an exception when I click [SHIFT]

another suggestion, why you don't directly use hazedumper ? I mean when the app started, you can download their JSON and use it. isn't that easier for you? you don't need to update yours on every update? 

on the old version I was able to replace yours with that ( request online and replace ) when something wrong happen, but seems like you made that a bit complicated on the new version  😅

**Comment by XanOpiat** [comment]
1. you dumb as hell man, mine is auto updating ergo faster than hazedumper
2. im working on the aimbot fix, but im obviously doing all of this for free and thus have other things to do like school or work

**Comment by badrsh** [comment]
First thanks for your kind words :) . I think I didn't say anything wrong to say ( I'm dumb ) otherwise you can write a note ( don't add any suggestion please to your readme, 😉 ). 
instead of you working on this manually on every update, why do you just not use the other one, that all I said. I know that all this open-source project is for free and thanks for all the effort put here. but anyway see yourself

**Comment by XanOpiat** [comment]
the cheat is updating it self, aka its faster than the hazedumper github which is updated manually on every update. and about the aimbot thing it would help if you gave futher info on the error message you are receiving as my aimbot is working perfectly fine

**Comment by Bugleman** [comment]
1. @badrsh, The dumb statement @XanOpiat  is referring to is "why you don't directly use hazedumper ?"
@XanOpiat Has came up with a better way to pull, offsets directly from the game!

2. @XanOpiat Already know's about the aimbot issues and is currently working to fix it, if you would like send the exception here.

**Comment by XanOpiat** [comment]
Fixed
