### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by FLUORESCENTXX** [XanOpiat/Python-CSGO-Cheat#85]
Doesn't inject into CSGO.exe. When I play and use the cmd python ProjectX_v2.py it opens i select the options, click update and nothing happens on the game.

**Comment by XanOpiat** [comment]
1. This is an external cheat, no library is injected into the process.
2. Is there any error in the cmd?
3. What options did you select?

**Comment by FLUORESCENTXX** [comment]
I just selected the glow and the cmd is fine.

**Comment by makerrii** [comment]
everything works fine for me.

**Comment by XanOpiat** [comment]
Yeah same for me, make sure you update the cheat and restart csgo
