### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pigeon-cn-0** [XanOpiat/Python-CSGO-Cheat#90]
Traceback (most recent call last):
  File "D:\Python-CSGO-Cheat-main\ProjectX_V2.py", line 12, in <module>
    from Classes.Ui import *
ModuleNotFoundError: No module named 'Classes.Ui'

**Comment by XanOpiat** [comment]
Im assuming you actually downloaded the entire project? do you have a "Classes" folder in your directory?

**Comment by pigeon-cn-0** [comment]
![image](https://user-images.githubusercontent.com/67412899/147848452-1af04c9c-3ad7-42a9-8fff-02313b4e9558.png)
yes

**Comment by pigeon-cn-0** [comment]
Resolved

**Comment by XanOpiat** [comment]
Nice
