### ISSUE TITLE
Aimbot not work.

### ISSUE THREAD

**Issue by Minerkinger** [XanOpiat/Python-CSGO-Cheat#94]
It stopped working after the last update. I think aimbot's smoothing setting is messing it up. Even if I set it to 1%, it stays very slow. Legit settings are almost useless. I suggest you make it simple again. Thanks.

**Comment by Bugleman** [comment]
Can you give more details?

Im kinda confused, is smoothing working and you just dont know what your talking about or is smoothing working.

I alerted QDK about this issue, but I suggest you to restart the cheat / run It as administrator as-well,
Post any updates here.

**Comment by XanOpiat** [comment]
Aimbot is fully working for me. Also you can just disable smoothing if you dont like it. The cheat can be used in a very way you want to also in simple ones

**Comment by Minerkinger** [comment]
I can say that my problem has been solved with the last update. Thanks.

**Comment by XanOpiat** [comment]
Great
