### ISSUE TITLE
Triggerbot Key Issue

### ISSUE THREAD

**Issue by Minerkinger** [XanOpiat/Python-CSGO-Cheat#95]
I can't assign the key I want. For example, when I type the "x" key into the space, I get an error like "Please Enter a Key". The "Alt" key is working for no reason. It was like this before, but you fixed it for a while, then you messed it up again. Thanks.

**Comment by Bugleman** [comment]
Im pretty sure this has been a known issue when I used this cheat sometimes the keybind's would error, I'm going to check the code, I think they updated the UI code recently.

**Comment by XanOpiat** [comment]
Updated code there actually was a very dumb mistake in the config code which had been there for a very long time, that prevented keybinds like "x" or "a"
