### ISSUE TITLE
One suggestion: RCS

### ISSUE THREAD

**Issue by Minerkinger** [XanOpiat/Python-CSGO-Cheat#96]
If you add an RCS like "https://github.com/ekknod/scripthial/blob/master/scripthial_windows.py#L13," it's going to be a lot more consistent because it's really messed up right now. In my example, the RCS is fine, but a little inconsistent. Thank you for listening to me.

**Comment by Minerkinger** [comment]
You also need to update the offsets when a new update has arrived.

**Comment by romybhae** [comment]
not working after v1404 update

**Comment by XanOpiat** [comment]
> You also need to update the offsets when a new update has arrived.

nope, just wrong, its self updating, sometimes big updates can break the code but thats rarely the case

**Comment by XanOpiat** [comment]
> If you add an RCS like "https://github.com/ekknod/scripthial/blob/master/scripthial_windows.py#L13," it's going to be a lot more consistent because it's really messed up right now. In my example, the RCS is fine, but a little inconsistent. Thank you for listening to me.

thanks for the idea to im gonna look at his code, and will try to implement it

**Comment by XanOpiat** [comment]
> > You also need to update the offsets when a new update has arrived.
> 
> nope, just wrong, its self updating, sometimes big updates can break the code but thats rarely the case

like it was today btw lol, everythings working again

**Comment by XanOpiat** [comment]
how about you add it yourself if its so easy.


im working on it, but im doing this for free and have similtanouesly go to school and work

**Comment by XanOpiat** [comment]
https://imgur.com/a/yPypK8U

Comparison video between the 2 rcs

**Comment by Minerkinger** [comment]
> https://imgur.com/a/yPypK8U
> 
> Comparison video between the 2 rcs

First of all, I see you've got me wrong;I just asked you, I don't have the luxury of giving you orders. Secondly, I'm not sure we use the same rcs. When I use the code you wrote, when I pull the trigger, the cursor throws itself into an irrelevant position. Could it be about resolution? Because I play 4:3 while you play 16:9. Thank you for listening to me. Good luck at school.

**Comment by XanOpiat** [comment]
Yeah no worries, i was just a bit tense. 
I mean this is the code i wrote, so im not necessarily sure what is wrong with it your end you know.
Maybe you could try setting:
mouse accelaration to "off"
raw input to "on"

maybe this fixes it

**Comment by XanOpiat** [comment]
In case this doesnt work, if you like you could also send me a video of how the rcs looks for you?
btw this doesnt happen because of resolution i have played with many resolutions before

**Comment by Minerkinger** [comment]
You were right and I solved the problem. Ram usage is low but CPU usage is high like 10-12%. This causes 10-15 fps drops. I've been using the codes you wrote since you released the old version. There was no such problem in the past because it wasn't that complicated. I see this fps drop as normal now. Thanks for everything. I wish you success in your life.

**Comment by XanOpiat** [comment]
Are you sure those fps drops are coming from the cpu usage of the cheat?
If you have a somewhat new cpu, counterstrike should never utilize all of your proccessors power, so 10-15 cpu usage should not cause any fps issues.
Also i believe to remember that the old cheat used to use a similar of computing power.
If youd like you can always go back to using the older version of the cheat in the OldVersion folder.
You might run into some issues with it tho so id be happy to help you.

Also are you sure these fps drops arent normal?
Because csgo fps can be very inconsistent and something as simple as firing a weapon can definetly cause a certain decrease in fps.

**Comment by Minerkinger** [comment]
I tested it and fps drops noticeably when cheat is on.

**Comment by Minerkinger** [comment]
In the old version Aimbot was not working so I stopped using it.

**Comment by XanOpiat** [comment]
> I tested it and fps drops noticeably when cheat is on.

what cpu do you have

**Comment by XanOpiat** [comment]
> In the old version Aimbot was not working so I stopped using it.

If you want to i can help you fix it

**Comment by XanOpiat** [comment]
> I tested it and fps drops noticeably when cheat is on.

What do you mean when you say noticeably? 
Also is this only happening when using rcs or when the cheat is running in general

**Comment by Minerkinger** [comment]
> 

1)Apparent / I meant obvious.

2)I realized that when I ran rcs and aimbo at the same time; They don't work. (I mean, that's the way it is with me.)

Is that what you're saying?

**Comment by Minerkinger** [comment]
> > I tested it and fps drops noticeably when cheat is on.
> 
> what cpu do you have

Intel Core i5-7200U @ 2.50Ghz

**Comment by Minerkinger** [comment]
> > In the old version Aimbot was not working so I stopped using it.
> 
> If you want to i can help you fix it

I'd appreciate that, but I don't think this is going to work because none of the other code scripts that look like it are working. This happened after a big update to this game, unfortunately I can't remember when it happened.

**Comment by XanOpiat** [comment]
> > > I tested it and fps drops noticeably when cheat is on.
> > 
> > 
> > what cpu do you have
> 
> Intel Core i5-7200U @ 2.50Ghz

yeah well thats definetly not a high end cpu, especially considering it is using an apu. So this might be the problem. You could try again once more tho, as today i implemented sleeping in the main loop which should hopefully help with your processors power

**Comment by Minerkinger** [comment]
I'll test it in a minute.

**Comment by Minerkinger** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/79358926/150634743-032f8d9d-6fc7-4060-a635-958b056923aa.PNG)

I guess the code not working right now. I've tried five times, turned the game off and on, but it's not working.

**Comment by XanOpiat** [comment]
For me it is, are you sure you are in a game?
Like not just in the main menu?
Also i just updated the OldCheatVersion file.
It is working again, but i have to tell you that despite what you say, it is using the same processor power as the new cheat (at least on my pc) so you most likely wont find any benefits performance wise.
I also fixed an error in the new cheat which would have caused it to not work anyway

**Comment by XanOpiat** [comment]
And i also have to tell you that im not going the keep improving the old cheat, im gonna leave it as it is and maybe update it once or twice, when needed but its definetly not my highest priority considering im always working on the latest cheat version.
This is why i strongly recommend you using the latest cheat version as it has more features, works better performance wise, and is just plain better

**Comment by XanOpiat** [comment]
Bot cheats are using 10% of my cpu btw

**Comment by Minerkinger** [comment]
:D

**Comment by XanOpiat** [comment]
?

**Comment by Minerkinger** [comment]
You're right, you're right.
