### ISSUE TITLE
Triggerbot stopps Glow

### ISSUE THREAD

**Issue by ElOxo** [XanOpiat/Python-CSGO-Cheat#99]
Glow is working fine until i press the tiggerbot key.
Then the Glow gets disabled until i release the triggerbot key.
after release of key the glow works fine again.

btw triggerbot dont work even if im infront of an enemy

**Comment by XanOpiat** [comment]
Sry man, forgot an import
should be fixed

**Comment by XanOpiat** [comment]
Maybe you could tell me if its fixed for you

**Comment by ElOxo** [comment]
yes iots working again TY
